CREATE TABLE "buddy_feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "associate_id" int NOT NULL,
  "buddy_id" integer NOT NULL,
  "feedback_date" timestamp NOT NULL,
  "feedback" text NOT NULL
);

CREATE TABLE "tp_associate" (
  "id" uuid PRIMARY KEY,
  "associate_id" integer UNIQUE,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "prev_account_name" varchar NOT NULL,
  "program_start_date" timestamp NOT NULL,
  "end_date" timestamp,
  "status" varchar,
  "techstack" varchar,
  "email_id" varchar,
  "phoneno" bigint
);

CREATE TABLE "buddy_table" (
  "id" uuid PRIMARY KEY,
  "buddy_id" integer UNIQUE,
  "buddy_name" varchar NOT NULL,
  "account_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "phno" bigint,
  "techstack" varchar,
  "no_associates_assigned" int
);

CREATE TABLE "associate_daily_task_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "associate_id" int NOT NULL,
  "task_status" text NOT NULL,
  "date" datetime NOT NULL
);

ALTER TABLE "buddy_feedback" ADD FOREIGN KEY ("associate_id") REFERENCES "tp_associate" ("associate_id");

ALTER TABLE "buddy_feedback" ADD FOREIGN KEY ("buddy_id") REFERENCES "buddy_table" ("buddy_id");

ALTER TABLE "associate_daily_task_status" ADD FOREIGN KEY ("associate_id") REFERENCES "tp_associate" ("associate_id");
